const quirkyPowers = [
  {
    id: 1,
    title: "Spontaneous Combustion",
    description: "Burst into flames at will without being harmed",
    atk: 85,
    def: 40,
    speed: 60,
  },
  {
    id: 2,
    title: "Temporal Hiccups",
    description: "Skip forward 3 seconds in time randomly",
    atk: 30,
    def: 50,
    speed: 95,
  },
  {
    id: 3,
    title: "Gravity Reversal",
    description: "Flip gravity's direction for yourself only",
    atk: 45,
    def: 60,
    speed: 70,
  },
  {
    id: 4,
    title: "Instant Noodles",
    description: "Summon perfectly cooked ramen from thin air",
    atk: 15,
    def: 80,
    speed: 55,
  },
  {
    id: 5,
    title: "Shadow Puppetry",
    description: "Animate shadows to do your bidding",
    atk: 70,
    def: 45,
    speed: 65,
  },
  {
    id: 6,
    title: "Bubblegum Blast",
    description: "Shoot explosive bubblegum projectiles",
    atk: 60,
    def: 35,
    speed: 75,
  },
  {
    id: 7,
    title: "Empathic Weather",
    description: "Your emotions control local weather patterns",
    atk: 55,
    def: 50,
    speed: 40,
  },
  {
    id: 8,
    title: "Molecular Disco",
    description: "Make molecules vibrate and glow rhythmically",
    atk: 50,
    def: 55,
    speed: 80,
  },
  {
    id: 9,
    title: "Eternal Hiccups",
    description: "Give anyone unstoppable hiccups for hours",
    atk: 20,
    def: 70,
    speed: 45,
  },
  {
    id: 10,
    title: "Liquid Limbs",
    description: "Turn your limbs into controllable liquid",
    atk: 65,
    def: 75,
    speed: 50,
  },
  {
    id: 11,
    title: "Pocket Dimension",
    description: "Store unlimited items in your pockets",
    atk: 25,
    def: 90,
    speed: 30,
  },
  {
    id: 12,
    title: "Sonic Sneeze",
    description: "Sneeze with the force of a sonic boom",
    atk: 75,
    def: 30,
    speed: 85,
  },
  {
    id: 13,
    title: "Plant Whisperer",
    description: "Communicate with and command plants",
    atk: 40,
    def: 85,
    speed: 35,
  },
  {
    id: 14,
    title: "Rubber Physics",
    description: "Bounce and stretch like rubber",
    atk: 55,
    def: 80,
    speed: 70,
  },
  {
    id: 15,
    title: "Memory Theft",
    description: "Steal and store others' memories temporarily",
    atk: 70,
    def: 40,
    speed: 60,
  },
  {
    id: 16,
    title: "Glitter Bomb",
    description: "Explode into harmless but annoying glitter",
    atk: 10,
    def: 60,
    speed: 90,
  },
  {
    id: 17,
    title: "Ice Cream Conjuring",
    description: "Create any flavor of ice cream instantly",
    atk: 15,
    def: 75,
    speed: 50,
  },
  {
    id: 18,
    title: "Echo Location",
    description: "See through walls using sound waves",
    atk: 35,
    def: 55,
    speed: 80,
  },
  {
    id: 19,
    title: "Probability Nudge",
    description: "Slightly increase odds in your favor",
    atk: 50,
    def: 50,
    speed: 50,
  },
  {
    id: 20,
    title: "Caffeine Absorption",
    description: "Absorb caffeine from any source for super speed",
    atk: 45,
    def: 40,
    speed: 95,
  },
  {
    id: 21,
    title: "Crystalline Armor",
    description: "Grow protective crystal shards on your skin",
    atk: 60,
    def: 95,
    speed: 25,
  },
  {
    id: 22,
    title: "Joke Manifestation",
    description: "Your jokes become temporarily real",
    atk: 55,
    def: 45,
    speed: 65,
  },
  {
    id: 23,
    title: "Magnetic Personality",
    description: "Attract or repel metal objects at will",
    atk: 70,
    def: 50,
    speed: 55,
  },
  {
    id: 24,
    title: "Instant Replay",
    description: "Replay the last 10 seconds of your life",
    atk: 30,
    def: 70,
    speed: 60,
  },
  {
    id: 25,
    title: "Origami Animation",
    description: "Bring paper creations to life",
    atk: 50,
    def: 55,
    speed: 70,
  },
  {
    id: 26,
    title: "Sympathetic Pain",
    description: "Transfer your injuries to inanimate objects",
    atk: 40,
    def: 85,
    speed: 45,
  },
  {
    id: 27,
    title: "Telekinetic Tickle",
    description: "Tickle people from a distance",
    atk: 15,
    def: 50,
    speed: 75,
  },
  {
    id: 28,
    title: "Aura Vision",
    description: "See people's emotional auras",
    atk: 25,
    def: 60,
    speed: 55,
  },
  {
    id: 29,
    title: "Density Control",
    description: "Alter your body's density at will",
    atk: 75,
    def: 80,
    speed: 40,
  },
  {
    id: 30,
    title: "Soap Bubble Shield",
    description: "Create indestructible soap bubbles",
    atk: 35,
    def: 90,
    speed: 50,
  },
  {
    id: 31,
    title: "Linguistic Mimicry",
    description: "Instantly speak any language you hear",
    atk: 20,
    def: 55,
    speed: 70,
  },
  {
    id: 32,
    title: "Bioluminescence",
    description: "Glow in the dark like a firefly",
    atk: 30,
    def: 50,
    speed: 65,
  },
  {
    id: 33,
    title: "Size Manipulation",
    description: "Shrink or grow up to 10x your size",
    atk: 80,
    def: 60,
    speed: 35,
  },
  {
    id: 34,
    title: "Dream Walking",
    description: "Enter and manipulate others' dreams",
    atk: 65,
    def: 45,
    speed: 55,
  },
  {
    id: 35,
    title: "Luck Vampire",
    description: "Drain luck from others to boost your own",
    atk: 55,
    def: 50,
    speed: 60,
  },
  {
    id: 36,
    title: "Molecular Adhesion",
    description: "Stick to any surface like Spider-Man",
    atk: 45,
    def: 65,
    speed: 80,
  },
  {
    id: 37,
    title: "Empathic Healing",
    description: "Heal others by taking their pain",
    atk: 20,
    def: 70,
    speed: 40,
  },
  {
    id: 38,
    title: "Lightning Rod",
    description: "Attract and redirect electricity",
    atk: 85,
    def: 55,
    speed: 75,
  },
  {
    id: 39,
    title: "Chameleon Skin",
    description: "Blend into any environment",
    atk: 40,
    def: 60,
    speed: 85,
  },
  {
    id: 40,
    title: "Sonic Scream",
    description: "Shatter glass and deafen foes with your voice",
    atk: 80,
    def: 35,
    speed: 70,
  },
  {
    id: 41,
    title: "Pheromone Control",
    description: "Emit pheromones to influence emotions",
    atk: 50,
    def: 55,
    speed: 60,
  },
  {
    id: 42,
    title: "Teleportation Sneeze",
    description: "Teleport randomly when you sneeze",
    atk: 35,
    def: 50,
    speed: 90,
  },
  {
    id: 43,
    title: "Object Animation",
    description: "Bring inanimate objects to life temporarily",
    atk: 60,
    def: 55,
    speed: 65,
  },
  {
    id: 44,
    title: "Photographic Reflexes",
    description: "Copy any physical move you see",
    atk: 70,
    def: 60,
    speed: 85,
  },
  {
    id: 45,
    title: "Acid Tears",
    description: "Cry tears that melt through anything",
    atk: 75,
    def: 40,
    speed: 50,
  },
  {
    id: 46,
    title: "Temporal Anchor",
    description: "Lock yourself in time, immune to changes",
    atk: 45,
    def: 95,
    speed: 20,
  },
  {
    id: 47,
    title: "Ink Manipulation",
    description: "Control and weaponize ink and paint",
    atk: 55,
    def: 50,
    speed: 70,
  },
  {
    id: 48,
    title: "Elastic Voice",
    description: "Throw your voice anywhere within 100 feet",
    atk: 30,
    def: 45,
    speed: 80,
  },
  {
    id: 49,
    title: "Selective Invisibility",
    description: "Turn invisible to specific people only",
    atk: 40,
    def: 65,
    speed: 75,
  },
  {
    id: 50,
    title: "Kinetic Battery",
    description: "Store kinetic energy and release it",
    atk: 85,
    def: 70,
    speed: 55,
  },
  {
    id: 51,
    title: "Fungal Growth",
    description: "Rapidly grow mushrooms and fungi",
    atk: 50,
    def: 75,
    speed: 40,
  },
  {
    id: 52,
    title: "Mirror Realm",
    description: "Step into mirrors and travel through them",
    atk: 55,
    def: 60,
    speed: 70,
  },
  {
    id: 53,
    title: "Emotion Vampirism",
    description: "Feed on others' emotions to sustain yourself",
    atk: 65,
    def: 55,
    speed: 60,
  },
  {
    id: 54,
    title: "Rust Touch",
    description: "Corrode metal with a touch",
    atk: 70,
    def: 45,
    speed: 50,
  },
  {
    id: 55,
    title: "Papercut Mastery",
    description: "Control paper to create devastating cuts",
    atk: 60,
    def: 35,
    speed: 85,
  },
  {
    id: 56,
    title: "Hive Mind Link",
    description: "Connect minds with willing participants",
    atk: 40,
    def: 60,
    speed: 55,
  },
  {
    id: 57,
    title: "Crystal Ball Summoning",
    description: "Summon a floating orb that shows the past",
    atk: 25,
    def: 50,
    speed: 45,
  },
  {
    id: 58,
    title: "Feather Fall",
    description: "Fall at the speed of a feather",
    atk: 20,
    def: 80,
    speed: 65,
  },
  {
    id: 59,
    title: "Confetti Explosion",
    description: "Explode into confetti and reform elsewhere",
    atk: 35,
    def: 55,
    speed: 95,
  },
  {
    id: 60,
    title: "Plasma Generation",
    description: "Create and manipulate superheated plasma",
    atk: 90,
    def: 45,
    speed: 60,
  },
  {
    id: 61,
    title: "Puppet Master",
    description: "Control people like marionettes",
    atk: 75,
    def: 40,
    speed: 50,
  },
  {
    id: 62,
    title: "Instant Garden",
    description: "Make plants grow to maturity instantly",
    atk: 35,
    def: 70,
    speed: 45,
  },
  {
    id: 63,
    title: "Technopathy",
    description: "Communicate with and control technology",
    atk: 65,
    def: 55,
    speed: 80,
  },
  {
    id: 64,
    title: "Poison Immunity",
    description: "Immune to all toxins and can secrete them",
    atk: 55,
    def: 85,
    speed: 50,
  },
  {
    id: 65,
    title: "Astral Projection",
    description: "Separate your spirit from your body",
    atk: 40,
    def: 90,
    speed: 70,
  },
  {
    id: 66,
    title: "Bone Manipulation",
    description: "Control and reshape your own skeleton",
    atk: 80,
    def: 75,
    speed: 40,
  },
  {
    id: 67,
    title: "Sound Theft",
    description: "Steal sounds from the environment",
    atk: 50,
    def: 60,
    speed: 65,
  },
  {
    id: 68,
    title: "Cartoon Physics",
    description: "Defy physics like a cartoon character",
    atk: 70,
    def: 80,
    speed: 90,
  },
  {
    id: 69,
    title: "Nightmare Fuel",
    description: "Manifest people's worst fears",
    atk: 85,
    def: 40,
    speed: 55,
  },
  {
    id: 70,
    title: "Molecular Reconstruction",
    description: "Reshape matter at molecular level",
    atk: 75,
    def: 65,
    speed: 35,
  },
  {
    id: 71,
    title: "Pollen Cloud",
    description: "Release clouds of various pollens",
    atk: 45,
    def: 55,
    speed: 70,
  },
  {
    id: 72,
    title: "Shockwave Stomp",
    description: "Create shockwaves by stomping",
    atk: 80,
    def: 60,
    speed: 45,
  },
  {
    id: 73,
    title: "Phase Shift",
    description: "Shift between dimensions briefly",
    atk: 60,
    def: 70,
    speed: 75,
  },
  {
    id: 74,
    title: "Empathic Shield",
    description: "Create barriers powered by emotions",
    atk: 35,
    def: 90,
    speed: 50,
  },
  {
    id: 75,
    title: "Silk Production",
    description: "Produce super-strong silk like a spider",
    atk: 55,
    def: 65,
    speed: 80,
  },
  {
    id: 76,
    title: "Thermal Vision",
    description: "See heat signatures through walls",
    atk: 45,
    def: 55,
    speed: 70,
  },
  {
    id: 77,
    title: "Vocal Mimicry",
    description: "Perfectly imitate any voice you've heard",
    atk: 30,
    def: 50,
    speed: 65,
  },
  {
    id: 78,
    title: "Quicksand Creation",
    description: "Turn solid ground into quicksand",
    atk: 65,
    def: 50,
    speed: 55,
  },
  {
    id: 79,
    title: "Adrenaline Surge",
    description: "Trigger extreme adrenaline at will",
    atk: 85,
    def: 40,
    speed: 95,
  },
  {
    id: 80,
    title: "Dust Devil",
    description: "Create and control miniature tornadoes",
    atk: 70,
    def: 50,
    speed: 80,
  },
  {
    id: 81,
    title: "Sensory Overload",
    description: "Amplify someone's senses painfully",
    atk: 75,
    def: 35,
    speed: 60,
  },
  {
    id: 82,
    title: "Holographic Projection",
    description: "Create realistic 3D holograms",
    atk: 40,
    def: 55,
    speed: 70,
  },
  {
    id: 83,
    title: "Blood Manipulation",
    description: "Control your blood outside your body",
    atk: 80,
    def: 60,
    speed: 55,
  },
  {
    id: 84,
    title: "Viral Adaptation",
    description: "Adapt to any virus or disease instantly",
    atk: 30,
    def: 95,
    speed: 45,
  },
  {
    id: 85,
    title: "Sand Sculptor",
    description: "Shape and harden sand into anything",
    atk: 60,
    def: 70,
    speed: 50,
  },
  {
    id: 86,
    title: "Radar Sense",
    description: "Sense your surroundings like echolocation",
    atk: 50,
    def: 60,
    speed: 75,
  },
  {
    id: 87,
    title: "Paint Reality",
    description: "Whatever you paint becomes real",
    atk: 70,
    def: 55,
    speed: 40,
  },
  {
    id: 88,
    title: "Telekinetic Thrust",
    description: "Push objects with your mind",
    atk: 75,
    def: 50,
    speed: 65,
  },
  {
    id: 89,
    title: "Swarm Control",
    description: "Command insects and small creatures",
    atk: 65,
    def: 45,
    speed: 70,
  },
  {
    id: 90,
    title: "Friction Manipulation",
    description: "Control friction on any surface",
    atk: 55,
    def: 60,
    speed: 85,
  },
  {
    id: 91,
    title: "Concussive Clap",
    description: "Create shockwaves by clapping",
    atk: 80,
    def: 45,
    speed: 60,
  },
  {
    id: 92,
    title: "Psychic Static",
    description: "Block telepathy and mental powers",
    atk: 25,
    def: 85,
    speed: 55,
  },
  {
    id: 93,
    title: "Viscosity Control",
    description: "Change the thickness of liquids",
    atk: 50,
    def: 65,
    speed: 60,
  },
  {
    id: 94,
    title: "Regeneration Burst",
    description: "Heal rapidly for 30 seconds",
    atk: 40,
    def: 90,
    speed: 50,
  },
  {
    id: 95,
    title: "Momentum Theft",
    description: "Steal kinetic energy from moving objects",
    atk: 70,
    def: 55,
    speed: 80,
  },
  {
    id: 96,
    title: "Blink Step",
    description: "Teleport short distances rapidly",
    atk: 60,
    def: 50,
    speed: 95,
  },
  {
    id: 97,
    title: "Flavor Manipulation",
    description: "Change how anything tastes",
    atk: 15,
    def: 55,
    speed: 50,
  },
  {
    id: 98,
    title: "Hardlight Constructs",
    description: "Create solid objects from light",
    atk: 75,
    def: 70,
    speed: 65,
  },
  {
    id: 99,
    title: "Empathic Illusion",
    description: "Create illusions based on emotions",
    atk: 55,
    def: 60,
    speed: 70,
  },
  {
    id: 100,
    title: "Seismic Sense",
    description: "Feel vibrations through the ground",
    atk: 45,
    def: 65,
    speed: 55,
  },
  {
    id: 101,
    title: "Decay Touch",
    description: "Age anything you touch rapidly",
    atk: 85,
    def: 40,
    speed: 50,
  },
  {
    id: 102,
    title: "Refraction Cloak",
    description: "Bend light around yourself",
    atk: 35,
    def: 75,
    speed: 80,
  },
  {
    id: 103,
    title: "Gravity Well",
    description: "Create localized gravity fields",
    atk: 80,
    def: 60,
    speed: 45,
  },
  {
    id: 104,
    title: "Spore Cloud",
    description: "Release clouds of various spores",
    atk: 50,
    def: 55,
    speed: 65,
  },
  {
    id: 105,
    title: "Temporal Dilation",
    description: "Slow time for yourself only",
    atk: 55,
    def: 70,
    speed: 90,
  },
  {
    id: 106,
    title: "Wax Manipulation",
    description: "Control and shape wax at will",
    atk: 45,
    def: 80,
    speed: 40,
  },
  {
    id: 107,
    title: "Sonar Blast",
    description: "Emit powerful sound waves",
    atk: 75,
    def: 45,
    speed: 70,
  },
  {
    id: 108,
    title: "Color Drain",
    description: "Remove color from anything",
    atk: 30,
    def: 50,
    speed: 60,
  },
  {
    id: 109,
    title: "Momentum Amplification",
    description: "Increase the force of moving objects",
    atk: 85,
    def: 50,
    speed: 75,
  },
  {
    id: 110,
    title: "Adaptive Camouflage",
    description: "Automatically blend into surroundings",
    atk: 40,
    def: 70,
    speed: 85,
  },
  {
    id: 111,
    title: "Pressure Point Master",
    description: "Instantly know where to strike",
    atk: 90,
    def: 55,
    speed: 80,
  },
  {
    id: 112,
    title: "Mist Form",
    description: "Transform into intangible mist",
    atk: 35,
    def: 85,
    speed: 70,
  },
  {
    id: 113,
    title: "Electric Eel",
    description: "Generate and discharge electricity",
    atk: 80,
    def: 50,
    speed: 65,
  },
  {
    id: 114,
    title: "Soul Vision",
    description: "See the true nature of people's souls",
    atk: 25,
    def: 60,
    speed: 55,
  },
  {
    id: 115,
    title: "Combustion Snap",
    description: "Create small explosions by snapping",
    atk: 75,
    def: 40,
    speed: 70,
  },
  {
    id: 116,
    title: "Empathy Amplifier",
    description: "Intensify emotions in others",
    atk: 50,
    def: 55,
    speed: 60,
  },
  {
    id: 117,
    title: "Glass Manipulation",
    description: "Shape and control glass freely",
    atk: 70,
    def: 65,
    speed: 55,
  },
  {
    id: 118,
    title: "Photosynthesis",
    description: "Gain energy from sunlight",
    atk: 30,
    def: 75,
    speed: 50,
  },
  {
    id: 119,
    title: "Echo Strike",
    description: "Your attacks hit twice with delay",
    atk: 85,
    def: 45,
    speed: 65,
  },
  {
    id: 120,
    title: "Magnetic Field",
    description: "Generate powerful magnetic fields",
    atk: 70,
    def: 60,
    speed: 60,
  },
  {
    id: 121,
    title: "Smoke Screen",
    description: "Generate thick concealing smoke",
    atk: 35,
    def: 70,
    speed: 80,
  },
  {
    id: 122,
    title: "Cellular Control",
    description: "Control your cells consciously",
    atk: 60,
    def: 85,
    speed: 45,
  },
  {
    id: 123,
    title: "Force Field Generator",
    description: "Create protective energy barriers",
    atk: 40,
    def: 95,
    speed: 40,
  },
  {
    id: 124,
    title: "Aura Reading",
    description: "Read power levels and intentions",
    atk: 35,
    def: 65,
    speed: 70,
  },
  {
    id: 125,
    title: "Tar Production",
    description: "Secrete sticky tar from your hands",
    atk: 55,
    def: 60,
    speed: 45,
  },
  {
    id: 126,
    title: "Vocal Blast",
    description: "Weaponize your voice into blasts",
    atk: 80,
    def: 40,
    speed: 75,
  },
  {
    id: 127,
    title: "Prism Refraction",
    description: "Split light into damaging beams",
    atk: 75,
    def: 50,
    speed: 80,
  },
  {
    id: 128,
    title: "Neural Shock",
    description: "Stun opponents with a touch",
    atk: 70,
    def: 45,
    speed: 65,
  },
  {
    id: 129,
    title: "Oil Slick",
    description: "Secrete slippery oil",
    atk: 40,
    def: 55,
    speed: 85,
  },
  {
    id: 130,
    title: "Pyrokinetic Aura",
    description: "Surround yourself with flames",
    atk: 85,
    def: 70,
    speed: 55,
  },
  {
    id: 131,
    title: "Density Punch",
    description: "Increase fist density for devastating hits",
    atk: 95,
    def: 50,
    speed: 50,
  },
  {
    id: 132,
    title: "Scent Manipulation",
    description: "Create or eliminate any smell",
    atk: 25,
    def: 60,
    speed: 65,
  },
  {
    id: 133,
    title: "Thorn Armor",
    description: "Grow protective thorns on your body",
    atk: 65,
    def: 85,
    speed: 40,
  },
  {
    id: 134,
    title: "Soundwave Surfing",
    description: "Ride on soundwaves",
    atk: 50,
    def: 55,
    speed: 90,
  },
  {
    id: 135,
    title: "Molecular Bonding",
    description: "Fuse objects together permanently",
    atk: 60,
    def: 65,
    speed: 50,
  },
  {
    id: 136,
    title: "Zero Point Energy",
    description: "Tap into quantum vacuum energy",
    atk: 90,
    def: 60,
    speed: 70,
  },
  {
    id: 137,
    title: "Petrification Gaze",
    description: "Turn things to stone with a look",
    atk: 85,
    def: 50,
    speed: 45,
  },
  {
    id: 138,
    title: "Slime Generation",
    description: "Produce versatile slime",
    atk: 45,
    def: 75,
    speed: 55,
  },
  {
    id: 139,
    title: "Vibration Sense",
    description: "Detect movement through vibrations",
    atk: 40,
    def: 60,
    speed: 80,
  },
  {
    id: 140,
    title: "Antimatter Touch",
    description: "Create small antimatter reactions",
    atk: 95,
    def: 30,
    speed: 60,
  },
  {
    id: 141,
    title: "Foam Fortress",
    description: "Generate hardening protective foam",
    atk: 30,
    def: 90,
    speed: 45,
  },
  {
    id: 142,
    title: "Psionic Blast",
    description: "Release mental energy attacks",
    atk: 80,
    def: 55,
    speed: 65,
  },
  {
    id: 143,
    title: "Limb Extension",
    description: "Stretch limbs up to 50 feet",
    atk: 65,
    def: 60,
    speed: 70,
  },
  {
    id: 144,
    title: "Cryogenic Breath",
    description: "Breathe freezing cold air",
    atk: 75,
    def: 50,
    speed: 60,
  },
  {
    id: 145,
    title: "Energy Vampire",
    description: "Drain energy from your surroundings",
    atk: 70,
    def: 65,
    speed: 55,
  },
  {
    id: 146,
    title: "Dimensional Pocket",
    description: "Access a personal pocket dimension",
    atk: 35,
    def: 80,
    speed: 50,
  },
  {
    id: 147,
    title: "Razor Wind",
    description: "Create cutting wind currents",
    atk: 80,
    def: 45,
    speed: 85,
  },
  {
    id: 148,
    title: "Berserk Mode",
    description: "Trade defense for massive attack boost",
    atk: 100,
    def: 20,
    speed: 75,
  },
  {
    id: 149,
    title: "Sandstorm Creation",
    description: "Summon localized sandstorms",
    atk: 65,
    def: 55,
    speed: 70,
  },
  {
    id: 150,
    title: "Perfect Balance",
    description: "Never lose your balance or fall",
    atk: 50,
    def: 70,
    speed: 80,
  },
];
export { quirkyPowers };
